plugins {
    id "application"
}

group = "com.example"
version = "0.1.0"

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

application {
    mainClass = "com.example.notification.Main"
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}
